name: Swift

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install swiftformat
      run: brew install swiftformat
    - name: Linting
      run: swiftformat --lint Sources --exclude AEPCore
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v      
